#f = open("CTX-M-27_sequence.txt", "r")

seq = "TTACAGCCCTTCGGCGATGATTCTCGCCGCTGAAGCCAGCACATCGCGGCGGCTCTCTGCGTTCTGTTGCGGCTGGGTAAAATAGGTCACCAGAACCAGCGGCGCACGACCCTGCGGCCAGATCACCGCAATATCATTGGTGGTGCCGTAGCCGCCGCTGCCGGTCTTATCACCCACAGTCCACGACGTCGGTAAGCCGGCCCGAATGCTGGCTGCGCCGGTCGTATTGCCTTTGAGCCACGTCACCAACTGCGCCCGCTGGGTTTCGCCCAGCGCATGACCCAGCGTAAGCTGACGCAACGTCTGCGCCATCGCCCGCGGCGTGGTGGTGTCTCTCGGGTCGCCGGGAATGGCGGTATTCAGCGTAGGTTCAGTGCGATCCAGACGAAACGTCTCATCGCCGATCGCGCGGGCAAAAGCCGTCACGCCTCCCGGGCCACCGAGCTGGGCAATCAATTTGTTCATGGCGGTATTGTCGCTGTACTGCAACGCGGCCGCGCTCAGTTCTGCCAGCGTCATTGTGCCGTTGACGTGTTTTTCGGCAATCGGATTGTAGTTAACCAGATCGGCAGGCTTGATCTCGACAGGCTGATTAAGCAGCTGCTTTTGCGTTTCACTCTGCTTAAGCACCGCCGCGGCCGCCATAACTTTACTGGTACTGCACATTGGAAAGCGTTCATCACCGCGATAAAGCACCTGCGTATTATCTGCGGTATCGATGAGCGCGACGCCCAGCCGCCCTCCGCTGCTTTTCTCCAGCGCCGCCAGCTTTTGCTGCACCGCACTCGTCTGCGCATAAAGCGGCGCGCTGCCCAGCAGCAGCGGAATGCACGCCGCCGCCGCGAACATCATCCGTTGCACTCTCTTTGTCACCAT"


def compliment (seq):
    newSeq  = ""
    for letter in seq:
        if letter == "T":
            newSeq += "A"
        if letter == "A":
            newSeq += "T"
        if letter == "C":
            newSeq += "G"
        if letter == "G":
            newSeq += "C"
    return newSeq

def reverse (seq):
    newSeq  = ""    
    for letter in seq:
        newSeq = letter + newSeq
       
    return newSeq
   

comp = compliment(seq)
final = reverse(comp)
print(final)


