seq = "TTGAATTCTATCAAAAAAATACTTCAAGCAAAATTATTAGTAAAAGGTAGAAAATTAGCGTATTTTGATTTAAATGGATTATGGATTGCTTTAAATGTTGAAGAAGATATACCAAGAAATGAAATTAAGCAATCTTATACACATATGGCTTTCACTGTAACTAATGAAGCATTAGACCATTTAAAAGAAGTATTAATTCAAAATGATGTTAATATTTTACCTGGCCGAGAAAGAGATGAGAGAGACCAAAGATCTCTTTACTTTACAGATCCAGATGGCCATAAGTTTGAGTTCCACACTGGCACTTTGCAAAACCGGTTAGAGTACTATAAAGAAGATAAAAAACATATGACTTTTTACATATAA"
seq = "ATGCTACAGGGCATTAACCATATTTGTTTTTCTGTATCAAACTTGGAAAAATCTATTGAATTCTATCAAAAAAATACTTCAAGCAAAATTATTAGTAAAAGGTAGAAAATTAGCGTATTTTGATTTAAATGGATTATGGATTGCTTTAAATGTTGAAGAAGATATACCAAGAAATGAAATTAAGCAATCTTATACACATATGGCTTTCACTGTAACTAATGAAGCATTAGACCATTTAAAAGAAGTATTAATTCAAAATGATGTTAATATTTTACCTGGCCGAGAAAGAGATGAGAGAGACCAAAGATCTCTTTACTTTACAGATCCAGATGGCCATAAGTTTGAGTTCCACACTGGCACTTTGCAAAACCGGTTAGAGTACTATAAAGAAGATAAAAAACATATGACTTTTTACATATAA"

print(len(seq))

AAs  =   "FFLLSSSSYY**CC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG"
Starts = "---M------**--*----M------------MMMM---------------M------------"
Base1  = "TTTTTTTTTTTTTTTTCCCCCCCCCCCCCCCCAAAAAAAAAAAAAAAAGGGGGGGGGGGGGGGG"
Base2  = "TTTTCCCCAAAAGGGGTTTTCCCCAAAAGGGGTTTTCCCCAAAAGGGGTTTTCCCCAAAAGGGG"
Base3  = "TCAGTCAGTCAGTCAGTCAGTCAGTCAGTCAGTCAGTCAGTCAGTCAGTCAGTCAGTCAGTCAG"

n = len(AAs)
d = {}

#for ch in AAs:
for i in range(n):
    codon = Base1[i] + Base2[i] + Base3[i]
    if codon not in d:
        d[codon] = AAs[i]
'''
if len(seq) % 3 == 0:
    m = len(seq) // 3
    mm = range(m)
else:
    remaind = len(seq) % 3
    lastoneortwo = len(seq)-remaind
    left = seq[lastoneortwo:]
    print(left)
    
    m = len(seq) // 3
    mm = range(m)
'''

left = ""

if len(seq) % 3 != 0:
    remaind = len(seq) % 3
    lastoneortwo = len(seq)-remaind
    left = seq[lastoneortwo:]

    
m = len(seq) // 3
mm = range(m)




AAseq = ""


for num in mm:
    cod = seq[0+3*num:3+3*num]
    AAseq += d[cod]
    #print(cod, d[cod])
print(AAseq, left)




    